---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tmaxcloud-acme-clusterissuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: yjs890403@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: ap-northeast-2
            # region: us-east-1
            accessKeyID: AKIA5D7L5Q3IXJWC5OFK
            secretAccessKeySecretRef:
              name: route53-secret
              key: secret-access-key
            hostedZoneID: Z0168768GHU66XKGU2VL

---
# Create secret
# kubectl create secret generic route53-secret --namespace cert-manager --from-literal=secret-access-key="DaLiLHqK2aLgSam8e4FYnCOuFwOIFxTQTrkLksx7"

