---
- name: gateway | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/gateway"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: gateway | Create Manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/console/{{ item.file }}"
  with_items:
    - { name: 1.crd, file: 1.crd.yml }
    - { name: 2.init, file: 2.init.yml }
    - { name: 3.job, file: 3.job.yml }
    - { name: 4.svc-clusterip, file: 4.svc-clusterip.yml }
    - { name: 5.deploy, file: 5.deploy.yml }
    - { name: 6.ingresss, file: 6.ingress.yml }
  register: console_manifests
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: gateway | Apply Manifests
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/console/{{ item.item.file }}"
    state: "latest"
    wait: true
  with_items:
    - "{{ console_manifests.results }}"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
  loop_control:
    label: "{{ item.item.file }}"
