apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: insecure@file
  name: shkim-aws-externalname
  namespace: shkim
spec:
  type: ExternalName
  externalName: shkim-aws-apiserver-205005065.eu-central-1.elb.amazonaws.com
