---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: ca-transport
  namespace: api-gateway-system
spec:
  certificatesSecrets:
    - tmaxca

---
apiVersion: v1
kind: Secret
metadata:
  name: tmaxca
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
#  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

