apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
  name: test-nginx
  namespace: test
spec:
  ingressClassName: tmax
  rules:
    ## nginx.{{ gateway에서 사용하는 기본 domain 주소 }}
    - host: nginx.tmaxcloud.org
      http:
        paths:
          - backend:
              service:
                name: test-nginx
                port:
                  number: 80
            path: /
            pathType: Prefix
