apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    createdTime: "2021-09-10T17:02:45.284354835+09:00"
    creator: kubernetes-admin
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: traefik-jwt-decode
    meta.helm.sh/release-namespace: default
    updatedTime: "2021-09-10T17:02:45.284354835+09:00"
    updater: kubernetes-admin
  creationTimestamp: "2021-09-10T08:02:45Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: traefik-jwt-decode
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-jwt-decode
    helm.sh/chart: traefik-jwt-decode-0.1.0
  name: traefik-jwt-decode
  namespace: default
  resourceVersion: "153634517"
  selfLink: /apis/apps/v1/namespaces/default/deployments/traefik-jwt-decode
  uid: 67711e8b-43e6-441e-b780-0762e2415b90
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-jwt-decode
      app.kubernetes.io/name: traefik-jwt-decode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: traefik-jwt-decode
        app.kubernetes.io/name: traefik-jwt-decode
    spec:
      containers:
      - env:
        - name: AUTH_HEADER_KEY
          value: Authorization
        - name: CACHE_ENABLED
          value: "true"
        - name: CLAIM_MAPPING_FILE_PATH
          value: /claim-mappings/config.json
        - name: JWKS_URL
          value: https://hyperauth.org/auth/realms/tmax/protocol/openid-connect/certs
        - name: LOG_LEVEL
          value: info
        - name: LOG_TYPE
          value: json
        - name: MAX_CACHE_KEYS
          value: "10000"
        - name: PORT
          value: "8080"
        - name: TOKEN_VALIDATED_HEADER_KEY
          value: jwt-token-validated
        image: simonschneider/traefik-jwt-decode:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: traefik-jwt-decode
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /claim-mappings
          name: claim-mappings
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: traefik-jwt-decode
        name: claim-mappings
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-10T08:03:05Z"
    lastUpdateTime: "2021-09-10T08:03:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-10T08:02:45Z"
    lastUpdateTime: "2021-09-10T08:03:05Z"
    message: ReplicaSet "traefik-jwt-decode-66977f478c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
