apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jwt-decode-auth
  namespace: api-gateway-system
spec:
  forwardAuth:
    address: http://traefik-jwt-decode.api-gateway-system.svc:8080
    authResponseHeaders:
      - jwt-token-validated
      - jwt-token-email
      - jwt-token-scopes
      - Authorization
    trustForwardHeader: true
    tls:
      insecureSkipVerify: true
