apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: console-ingressroute
  namespace: api-gateway-system
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: PathPrefix(`/`, `/static/`, `/api/resource/`) && Host(`*`)
    services:
    - name: console-service@file
      kind: TraefikService
  tls: {} # use default tls 
    # secretName: console-tls