
# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth
  namespace: api-gateway-system
type: Opaque
data:
  PROVIDERS_OIDC_CLIENT_SECRET: Yjc3MTI1ZGItMTI0Yy00M2U5LWE3M2QtYzdlNWYwNTM5NDFi
  SECRET: MzA4NWEwYjY0OTkzMWM0NDkxYzRlMDgwYTlhZjcwZWYK