apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: api-gateway-system
spec:
  forwardAuth:
    address: http://traefik-forward-auth.api-gateway-system.svc:4181
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
    # tls:
    #   insecureSkipVerify: true