apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik-jwt-decode
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-jwt-decode
    helm.sh/chart: traefik-jwt-decode-0.1.0
  name: traefik-jwt-decode
  namespace: api-gateway-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: traefik-jwt-decode
    app.kubernetes.io/name: traefik-jwt-decode
  type: ClusterIP
