---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
 labels:
  app.kubernetes.io/instance: traefik
  app.kubernetes.io/managed-bu: tmax-cloud
  app.kubernetes.io/name: api-gateway
 name: insecure-transport
 namespace: api-gateway-system
spec:
 insecureSkipVerify: true
